name = "dream_test"
version = "2.1.0"
description = "A testing framework for Gleam that gets out of your way"
licences = ["MIT"]
repository = { type = "github", user = "TrustBound", repo = "dream_test" }
links = [{ title = "Documentation", href = "https://hexdocs.pm/dream_test" }]

[dependencies]
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0 and < 1.0.0"

[dev-dependencies]
